/**
 * This is the build script file
 * that helps to generate the final component structure
 * @author: Niranjan Kumar
 */
const fse = require("fs-extra");
const fs = require("fs");
const glob = require("glob");
const path = require("path");
const sass = require("sass");
const {compilerOptions: tsconfig} = require('./tsconfig.json');
const { incluecomp } = require('./package.json');

/* Config Variables */
const temp = incluecomp.tempStyleFolder;
const style = `${temp}/styles/`;
const baseSrc = tsconfig.rootDir;
const finalBuildFolder = tsconfig.outDir;

function copyFiles(src, dest) {
  const srcDir = glob.sync(src + "/**");
  srcDir.map((file) => {
    try {
      let _dest = file.replace(src + "/", dest);

      const outBuf = fs.readFileSync(file, "utf8");
      fse.outputFileSync(_dest, outBuf);
    } catch (e) {
      if (e.code === "EISDIR") { // Ignore for Directories
        console.log("Ignoring the code: EISDIR -> ", file);
      } else {
        throw e;
      }
    }
  });
}

// Modify the source to include the common @imports from style folders
const source = glob.sync(`${baseSrc}/**/*.scss`, { ignore: `${baseSrc}/stories/**`});
source.map((file) => {
  let dest = file.replace(baseSrc, temp);

  let rStyle = dest.split("/");
  rStyle.pop();
  rStyle = rStyle.join("/");
  rStyle = path.posix.relative(rStyle, style);

  const outBuff = `
    /*Generated by build script*/
    ${incluecomp.commonStyleImports
      .map((file)=> `@import '${rStyle + file}';\n`).
      join('')}

		${fs.readFileSync(file, "utf8")}
	`;

  fse.outputFileSync(dest, outBuff);
});

// Copy to styles to __scss__/styles to process SCSS
copyFiles("src/styles", style);

//Final processed files -> Copy to destination folder finalBuildFolder
const _scss_ = glob.sync(temp + "/**/*.scss", { ignore: temp + "/styles/**" });
_scss_.map((file) => {
  const dest = file.replace(temp, finalBuildFolder);
  const scss = sass.renderSync({ file: file });
  fse.outputFileSync(dest, scss.css);
});

//Copy assets to finalBuildFolder
const images = glob.sync(`${baseSrc}/components/**/*.{svg,gif}`);
images.map((file) => {
  let dest = file.replace(baseSrc, finalBuildFolder);
  const outBuff = fs.readFileSync(file, "utf8");
  fse.outputFileSync(dest, outBuff);
});
